# Site settings
title: Jacob T. Fisher
subtitle: 
email: jacob.taylor.fisher@gmail.com
description: Researcher, Media Neuroscience Lab | Graduate student, UC Santa Barbara
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Jacob T. Fisher
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# Social settings
university_affiliation: University of Illinois
university_url: https://illinois.edu/
departmental_affiliation: College of Media
departmental_url: https://media.illinois.edu/
rg_url: https://www.researchgate.net/profile/Jacob_Fisher4
github_url: https://github.com/jacobtfisher
orcid_url: https://orcid.org/0000-0002-2968-2557
osf_url: https://osf.io/n49b8/
twitter_url: https://twitter.com/jake_fisher

# Build settings
markdown: kramdown
sass:
    sass_dir: _sass

collections:
  pubs:
    output: true
    permalink: /pubs/:title
  courses:
    output: true
    permaling: /courses/:title